name: zen_fit_hub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 
  flutter_localizations: 
    sdk: flutter
 
  # Statemanagemant
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Local storage
  shared_preferences: ^2.2.2

  # Image
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9

  # Authentication
  google_sign_in: ^5.0.7
  
  # Firebase
  firebase_core: ^2.25.3
  cloud_firestore: ^4.15.3
  firebase_storage: ^11.6.5
  firebase_auth: ^4.17.4
  # 
  # Error 
  logging: ^1.2.0
  dartz: ^0.10.1
  
  internet_connection_checker: ^1.0.0+1
  
  # response
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.7
  
  sqflite: ^2.3.2
  path: ^1.8.3
  flutter_offline: ^3.0.1
  path_provider: ^2.1.2
  quickalert: ^1.0.2
  uuid: ^4.3.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/icons/
  fonts: 
    - family: DM Sans
      fonts: 
        - asset: assets/fonts/DMSansBold.ttf
          weight: 700
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
        - asset: assets/fonts/DMSansRegular.ttf
          weight: 400
    - family: Bebas Neue
      fonts: 
        - asset: assets/fonts/BebasNeueRegular.ttf
          weight: 400
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratRomanBold.ttf
          weight: 700
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Bebas
      fonts: 
        - asset: assets/fonts/BebasRegular.ttf
          weight: 400

